spring:
  kafka:
    bootstrap-server: "localhost:9092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "ru.practicum.telemetry.serialization.AvroSerializer"

topic:
  hub-event: "telemetry.hubs.v1"
  sensor-event: "telemetry.sensors.v1"
grpc:
  server:
    port: 59091